### ISSUE TITLE
issue with submodules

### ISSUE THREAD

**Issue by dyollb** [danielyan86129/voxel_ma#1]
i found your paper and [website](https://yajieyan.github.io/publication/voxelcore/overview/) and would like to try the code, but unfortunately cloning the submodules doesn't work for me. This is what I get

```bash
Submodule '3rdparty/ann' (git@github.com:danielyan86129/ann.git) registered for path '3rdparty/ann'
Submodule '3rdparty/isosurface_tao' (git@github.com:danielyan86129/isosurface_tao.git) registered for path '3rdparty/isosurface_tao'
Submodule '3rdparty/ply' (git@github.com:danielyan86129/ply.git) registered for path '3rdparty/ply'
Submodule '3rdparty/tetgen' (git@github.com:danielyan86129/tetgen.git) registered for path '3rdparty/tetgen'
Submodule '3rdparty/trimesh2' (git@github.com:danielyan86129/trimesh2.git) registered for path '3rdparty/trimesh2'
Cloning into '/Users/lloyd/Code/VoxelCores/3rdparty/ann'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:danielyan86129/ann.git' into submodule path '/Users/lloyd/Code/VoxelCores/3rdparty/ann' failed
Failed to clone '3rdparty/ann'. Retry scheduled
Cloning into '/Users/lloyd/Code/VoxelCores/3rdparty/isosurface_tao'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:danielyan86129/isosurface_tao.git' into submodule path '/Users/lloyd/Code/VoxelCores/3rdparty/isosurface_tao' failed
Failed to clone '3rdparty/isosurface_tao'. Retry scheduled
Cloning into '/Users/lloyd/Code/VoxelCores/3rdparty/ply'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:danielyan86129/ply.git' into submodule path '/Users/lloyd/Code/VoxelCores/3rdparty/ply' failed
Failed to clone '3rdparty/ply'. Retry scheduled
Cloning into '/Users/lloyd/Code/VoxelCores/3rdparty/tetgen'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:danielyan86129/tetgen.git' into submodule path '/Users/lloyd/Code/VoxelCores/3rdparty/tetgen' failed
Failed to clone '3rdparty/tetgen'. Retry scheduled
Cloning into '/Users/lloyd/Code/VoxelCores/3rdparty/trimesh2'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:danielyan86129/trimesh2.git' into submodule path '/Users/lloyd/Code/VoxelCores/3rdparty/trimesh2' failed
Failed to clone '3rdparty/trimesh2'. Retry scheduled
Cloning into '/Users/lloyd/Code/VoxelCores/3rdparty/ann'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

etc.
```

**Comment by danielyan86129** [comment]
Can you try cloning using the http url? The url you use requires you to add your ssh public key in your git profile. Did you set it up by the way? If not you can follow the instructions given by GitHub on how to add ssh key.Sent from my iPhoneOn Jan 26, 2023, at 12:54 AM, Bryn Lloyd ***@***.***> wrote:﻿
i found your paper and website and would like to try the code, but unfortunately cloning the submodules doesn't work for me. This is what I get
Submodule '3rdparty/ann' ***@***.***:danielyan86129/ann.git) registered for path '3rdparty/ann'
Submodule '3rdparty/isosurface_tao' ***@***.***:danielyan86129/isosurface_tao.git) registered for path '3rdparty/isosurface_tao'
Submodule '3rdparty/ply' ***@***.***:danielyan86129/ply.git) registered for path '3rdparty/ply'
Submodule '3rdparty/tetgen' ***@***.***:danielyan86129/tetgen.git) registered for path '3rdparty/tetgen'
Submodule '3rdparty/trimesh2' ***@***.***:danielyan86129/trimesh2.git) registered for path '3rdparty/trimesh2'
Cloning into '/Users/lloyd/Code/VoxelCores/3rdparty/ann'...
***@***.***: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of ***@***.***:danielyan86129/ann.git' into submodule path '/Users/lloyd/Code/VoxelCores/3rdparty/ann' failed
Failed to clone '3rdparty/ann'. Retry scheduled
Cloning into '/Users/lloyd/Code/VoxelCores/3rdparty/isosurface_tao'...
***@***.***: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of ***@***.***:danielyan86129/isosurface_tao.git' into submodule path '/Users/lloyd/Code/VoxelCores/3rdparty/isosurface_tao' failed
Failed to clone '3rdparty/isosurface_tao'. Retry scheduled
Cloning into '/Users/lloyd/Code/VoxelCores/3rdparty/ply'...
***@***.***: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of ***@***.***:danielyan86129/ply.git' into submodule path '/Users/lloyd/Code/VoxelCores/3rdparty/ply' failed
Failed to clone '3rdparty/ply'. Retry scheduled
Cloning into '/Users/lloyd/Code/VoxelCores/3rdparty/tetgen'...
***@***.***: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of ***@***.***:danielyan86129/tetgen.git' into submodule path '/Users/lloyd/Code/VoxelCores/3rdparty/tetgen' failed
Failed to clone '3rdparty/tetgen'. Retry scheduled
Cloning into '/Users/lloyd/Code/VoxelCores/3rdparty/trimesh2'...
***@***.***: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of ***@***.***:danielyan86129/trimesh2.git' into submodule path '/Users/lloyd/Code/VoxelCores/3rdparty/trimesh2' failed
Failed to clone '3rdparty/trimesh2'. Retry scheduled
Cloning into '/Users/lloyd/Code/VoxelCores/3rdparty/ann'...
***@***.***: Permission denied (publickey).
fatal: Could not read from remote repository.

etc.

**Comment by dyollb** [comment]
ah. you're right, sorry. my key expired ...
